# This is a YAML file 
preprocessing: # preprocessing options
  baseline_correction:
    method: airPLS
    lam: 0.001 
    diff_order: 1
    max_iter: 15
    tol: 0.001
    weights: None
  cosmic_ray_removal:
    method: WHzscores
    kernel_size: 3
    threshold: 3.5
  smoothing:
    method: SavitzkyGolay
    window_length: 9
    polyorder: 2

normalization: # normalization options
  normalization_type_options:
    - by_area
    - by_max

amplification: # spectrum_amplifying_factor
  spectrum_amplifying_factor: 
    low: 20
    high: 40  # Uniform

shot_noise: # photon shot noise
  noise_type: poisson
  lam: 
    low: 5 # lambda for poisson noise
    high: 15

dark_current_noise: #dark_current_shot_noise
  noise_type: poisson
  lam: 
    low: 5 # lambda for poisson noise
    high: 15

photo_response_non_uniformity: #photo_response_non_uniformity
  noise_type: gaussian
  mean: 
    low: 0.01
    high: 0.05
  std: 
    low: 0.001
    high: 0.005

FPN_noise: #dark_signal_FPN_noise
  noise_type: lognormal
  mean: 
    low: 0.05
    high: 0.1
  sigma: 
    low: 0.001
    high: 0.005

horizontal_shift: #instrumental_horizontal_shift
  low: 0.5
  high: 1.5
  # The unit is cm-1   

convoluting_gaussian:
  guassian_std:
    low: 0.3 # gussian std
    high: 0.8

cosmic_ray:
  spike_number: 
    low: 0
    high: 5 
  spike_amplitude: 
    low: 2
    high: 5

baseline: 
  baseline_type_options: 
    - poly
  baseline_amplification_multiplier: 
    low: 0.1
    high: 0.5 # Uniform
  poly_orders: 
    low: 2
    high: 4
  poly_coefficients:
    low: 0.0000005
    high: 0.000005
  sine:
    sine_amplitude: 
      low: 1
      high: 5
    sine_frequency: 
      low: 2
      high: 15
    sine_phase:
      low: 0
      high: 2
