# This is a YAML file 
metabolomics_file_path: metabolomics.xlsx
sample_type: Saliva # or Plasma, Serum

DFT_file_path: raman_rpbe_1106.pickle

laser_wavelength: 785

raman_shift_range_pars: 
  - 350 
  - 1800 
  - 1450

normalization_option_for_individual_spectrum: area # or max

normalization_option_for_mixture_spectrum: area # or max

# spectrum_amplifying_factor
spectrum_amplifying_factor: 20  # Uniform, [low, high]
baseline_amplifying_factor: 20  # Uniform, [low, high]

shot_noise_pars: 
  noise_type: poisson
  lam: 1 # lambda for poisson noise

instrumment_shift: 1
  # The unit is cm-1   

abbreviation_pars: 
  kernel_std: 4

cosmic_ray_pars:
  spike_num: 0 
  spike_amplitude: 1 

baseline_type: poly # sine
poly:
  poly_orders: 2
  poly_coefficients:
    - 0.01 # coef for zero order
    - 0.00001 # coef for second order
    - 0.000001 # coef for third order...
    - 0.000003 # coef for fourth order...
  poly_displacement:    # Normal distribution [mean standard_deviation][0, 300]
    - 0
    - -680
    - 0
sine:
  sine_amplitude: 1 
  sine_frequency: 5 
  sine_phase: 1

gaussian_pars:
  # Amplitude of the Gaussian peaks in a spectrum (signal intensity level)
  w: 0.05 
  mw: 0.1
  m: 0.2
  ms: 0.25
  s: 0.5
  vs: 1  
  # Sigma of the Gaussian peaks in a spectrum (signal peak shape)
  n: 5 
  sh: 10
  br: 15
