name: ygtest
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - yaml
  - pandas
  - pickle
  - seaborn
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - ramanspy
    - lightning
    - lightly