# This is a YAML file 
metabolomics_file_path: /Users/yifeigu/Documents/Carney_Lab/NoodleSpy/noodlespy/data/metabolomics.xlsx
sample_type: Saliva # or Plasma, Serum

DFT_file_path: /Users/yifeigu/Documents/Carney_Lab/NoodleSpy/noodlespy/data/raman_rpbe_1106.pickle

laser_wavelength: 785
exposure_time: 30 # seconds
quantumn_efficiency: 0.95

raman_shift_range_pars: 
  start_wavenumber: 350 
  end_wavenumber: 1800
  step_wavenumber: 1 

normalization_option_for_individual_spectrum: area # or max

normalization_option_for_mixture_spectrum: area # or max

# spectrum_amplifying_factor
spectrum_amplifying_factor: 40  # Uniform, [low, high]
baseline_amplifying_factor: 1 # Uniform, [low, high]

photon_shot_noise_pars: 
  noise_type: poisson
  lam: 1 # lambda for poisson noise

dark_current_shot_noise_pars: 
  noise_type: poisson
  lam: 1 # lambda for poisson noise

photo_response_non_uniformity_pars:
  noise_type: gaussian
  mean: 0.5
  std: 1

dark_signal_FPN_noise_pars:
  noise_type: lognormal
  mean: 0.5
  sigma: 1

instrument_shift: 1
  # The unit is cm-1   

abbrration_kernel_std: 4

cosmic_ray_pars:
  spike_num: 0 
  spike_amplitude: 1 

baseline_pars: 
  baseline_type: poly # sine
  poly_orders: 2
  poly_coefficients:
    - 0.00001 # coef for zero order
    - 0.000001 # coef for second order
    - 0.0000001 # coef for third order...
    - 0.00000003 # coef for fourth order...
  poly_displacement:    # Normal distribution [mean standard_deviation][0, 300]
    - 0
    - -12
    - 0
    - 0
    
sine:
  sine_amplitude: 1
  sine_frequency: 5
  sine_phase: 1

gaussian_pars:
  # Amplitude of the Gaussian peaks in a spectrum (signal intensity level)
  w: 0.05 
  mw: 0.1
  m: 0.2
  ms: 0.25
  s: 0.5
  vs: 1  
  # Sigma of the Gaussian peaks in a spectrum (signal peak shape)
  n: 5 
  sh: 10
  br: 15
